require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppParametersController do

  # This should return the minimal set of attributes required to create a valid
  # AppParameter. As you add validations to AppParameter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "group" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppParametersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all app_parameters as @app_parameters" do
      app_parameter = AppParameter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:app_parameters).should eq([app_parameter])
    end
  end

  describe "GET show" do
    it "assigns the requested app_parameter as @app_parameter" do
      app_parameter = AppParameter.create! valid_attributes
      get :show, {:id => app_parameter.to_param}, valid_session
      assigns(:app_parameter).should eq(app_parameter)
    end
  end

  describe "GET new" do
    it "assigns a new app_parameter as @app_parameter" do
      get :new, {}, valid_session
      assigns(:app_parameter).should be_a_new(AppParameter)
    end
  end

  describe "GET edit" do
    it "assigns the requested app_parameter as @app_parameter" do
      app_parameter = AppParameter.create! valid_attributes
      get :edit, {:id => app_parameter.to_param}, valid_session
      assigns(:app_parameter).should eq(app_parameter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppParameter" do
        expect {
          post :create, {:app_parameter => valid_attributes}, valid_session
        }.to change(AppParameter, :count).by(1)
      end

      it "assigns a newly created app_parameter as @app_parameter" do
        post :create, {:app_parameter => valid_attributes}, valid_session
        assigns(:app_parameter).should be_a(AppParameter)
        assigns(:app_parameter).should be_persisted
      end

      it "redirects to the created app_parameter" do
        post :create, {:app_parameter => valid_attributes}, valid_session
        response.should redirect_to(AppParameter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved app_parameter as @app_parameter" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppParameter.any_instance.stub(:save).and_return(false)
        post :create, {:app_parameter => { "group" => "invalid value" }}, valid_session
        assigns(:app_parameter).should be_a_new(AppParameter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppParameter.any_instance.stub(:save).and_return(false)
        post :create, {:app_parameter => { "group" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested app_parameter" do
        app_parameter = AppParameter.create! valid_attributes
        # Assuming there are no other app_parameters in the database, this
        # specifies that the AppParameter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AppParameter.any_instance.should_receive(:update).with({ "group" => "" })
        put :update, {:id => app_parameter.to_param, :app_parameter => { "group" => "" }}, valid_session
      end

      it "assigns the requested app_parameter as @app_parameter" do
        app_parameter = AppParameter.create! valid_attributes
        put :update, {:id => app_parameter.to_param, :app_parameter => valid_attributes}, valid_session
        assigns(:app_parameter).should eq(app_parameter)
      end

      it "redirects to the app_parameter" do
        app_parameter = AppParameter.create! valid_attributes
        put :update, {:id => app_parameter.to_param, :app_parameter => valid_attributes}, valid_session
        response.should redirect_to(app_parameter)
      end
    end

    describe "with invalid params" do
      it "assigns the app_parameter as @app_parameter" do
        app_parameter = AppParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_parameter.to_param, :app_parameter => { "group" => "invalid value" }}, valid_session
        assigns(:app_parameter).should eq(app_parameter)
      end

      it "re-renders the 'edit' template" do
        app_parameter = AppParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_parameter.to_param, :app_parameter => { "group" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested app_parameter" do
      app_parameter = AppParameter.create! valid_attributes
      expect {
        delete :destroy, {:id => app_parameter.to_param}, valid_session
      }.to change(AppParameter, :count).by(-1)
    end

    it "redirects to the app_parameters list" do
      app_parameter = AppParameter.create! valid_attributes
      delete :destroy, {:id => app_parameter.to_param}, valid_session
      response.should redirect_to(app_parameters_url)
    end
  end

end
